version: 2

updates:

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    assignees:
      - "thomaslaurenson"

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 0  # only security updates
    assignees:
      - "thomaslaurenson"

  - package-ecosystem: docker
    directory: /app
    schedule:
      interval: weekly
    open-pull-requests-limit: 0  # only security updates
    assignees:
      - "thomaslaurenson"
